# Taken from nova_common
float32 talon0Velocity # left middle
float32 talon1Velocity # left front
float32 talon2Velocity # left rear
float32 talon3Velocity # right middle
float32 talon4Velocity # right front
float32 talon5Velocity # right rear

float32 talon0Position # left middle
float32 talon1Position # left front
float32 talon2Position # left rear
float32 talon3Position # right middle
float32 talon4Position # right front
float32 talon5Position # right rear

